require 'ringioAPI/base.rb'

require 'ringioAPI/account.rb'
require 'ringioAPI/contact.rb'
require 'ringioAPI/feed.rb'
require 'ringioAPI/note.rb'
require 'ringioAPI/chat.rb'
require 'ringioAPI/ring.rb'
require 'ringioAPI/user.rb'
require 'ringioAPI/number.rb'
require 'ringioAPI/call.rb'
require 'ringioAPI/hangup.rb'
